Sub main
	Dim oDoc As Document = ThisDoc.Document
	If Not TypeOf oDoc Is PartDocument Then Exit Sub
	Dim oPDoc As PartDocument = oDoc
	If oPDoc.ComponentDefinition.SurfaceBodies.Count = 0 Then Exit Sub
	Dim oBody As SurfaceBody = oPDoc.ComponentDefinition.SurfaceBodies(1)
	Dim oProfile As Profile
	Try : oProfile = oBody.CreatedByFeature.Profile
	Catch : MessageBox.Show("Failed to get profile of sketch.", "Error!") : Exit Sub
	End Try
	Dim dIxx, dIyy, dIzz, dIxy, dIyz, dIxz, dIx, dIy, dIz, dKxx, dKyy, dKzz As Double
	Dim oRegProps As RegionProperties = oProfile.RegionProperties
	Logger.Info(" Profile properties:")	
	Logger.Info(" Area = " & Round(oRegProps.Area, 3) & " cm2")
	Logger.Info(" Perimeter = " & Round(oRegProps.Perimeter, 3) & " cm")
	oRegProps.CentroidMomentsOfInertia(dIxx, dIyy, dIzz, dIxy, dIyz, dIxz)
	Logger.Info(" Z0(X) = " & Round(oRegProps.Centroid.X, 5) & " cm")
	Logger.Info(" Z0(Y) = " & Round(oRegProps.Centroid.Y, 5) & " cm")
'	Logger.Info(" Ixx = " & Round(dIxx, 5) & " cm4")
'	Logger.Info(" Iyy = " & Round(dIyy, 5) & " cm4")
'	Logger.Info(" Izz = " & Round(dIzz, 5) & " cm")
'	Logger.Info(" Ixy = " & Round(dIxy, 5) & " cm")
'	Logger.Info(" Iyz = " & Round(dIyz, 5) & " cm")
'	Logger.Info(" Ixz = " & Round(dIxz, 5) & " cm")
	oRegProps.MomentsOfInertia(dIxx, dIyy, dIzz, dIxy, dIyz, dIxz)
	Logger.Info(" Ixx = " & Round(dIxx, 5) & " cm4")
	Logger.Info(" Iyy = " & Round(dIyy, 5) & " cm4")
'	Logger.Info(" Izz = " & Round(dIzz, 5) & " cm")
'	Logger.Info(" Ixy = " & Round(dIxy, 5) & " cm")
'	Logger.Info(" Iyz = " & Round(dIyz, 5) & " cm")
'	Logger.Info(" Ixz = " & Round(dIxz, 5) & " cm")
	oRegProps.PrincipalMomentsOfInertia(dIx, dIy, dIz)
	Logger.Info(" Ix = " & Round(dIx, 5) & " cm4")
	Logger.Info(" Iy = " & Round(dIy, 5) & " cm4")
'	Logger.Info(" Iz = " & Round(dIz, 5) & " cm4")
	oRegProps.RadiusOfGyration(dKxx, dKyy, dKzz)
	Logger.Info(" Kxx = " & Round(dKxx, 5) & " cm")
	Logger.Info(" Kyy = " & Round(dKyy, 5) & " cm")
'	Logger.Info(" Kzz = " & Round(dKzz, 5) & " cm3")
End Sub