Dim oDoc As PartDocument = ThisDoc.Document
If oDoc.FileSaveCounter = 0 Then Exit Sub
Dim oUOfM As UnitsOfMeasure = oDoc.UnitsOfMeasure
Dim oInvSummInfo As PropertySet = oDoc.PropertySets("Inventor Summary Information")
Dim oDocSummInfo As PropertySet = oDoc.PropertySets("Inventor Document Summary Information")
Dim oDesTrackProps As PropertySet = oDoc.PropertySets("Design Tracking Properties")
Dim oInvUserInfo As PropertySet = oDoc.PropertySets("Inventor User Defined Properties")
Dim oDocDef As PartComponentDefinition = oDoc.ComponentDefinition
Dim oUsParams As UserParameters = oDocDef.Parameters.UserParameters

Dim L_size As Double
Dim WebLink As String = oDesTrackProps("Catalog Web Link").Value
If WebLink = "ДСТУ 4747" Or WebLink = "ДСТУ 4738" Then
	L_size = oUOfM.ConvertUnits(oUsParams("G_L").Value, UnitsTypeEnum.kCentimeterLengthUnits, oUOfM.LengthUnits)
Else
	L_size = oUOfM.ConvertUnits(oUsParams("B_L").Value, UnitsTypeEnum.kCentimeterLengthUnits, oUOfM.LengthUnits)
End If
If L_size = 0 Then
	L_size = Measure.ExtentsHeight
End If
Dim sName As String = System.IO.Path.GetFileNameWithoutExtension(oDoc.FullFileName)	
If oDesTrackProps("Part Number").Value <> sName.Substring(0, sName.IndexOf(" ")) Then
	oDesTrackProps("Part Number").Value = sName.Substring(0, sName.IndexOf(" "))
End If
If oInvSummInfo("Title").Value <> sName.Remove(0, sName.IndexOf(" ") + 1) Then
	oInvSummInfo("Title").Value = sName.Remove(0, sName.IndexOf(" ") + 1)
End If		
Dim NumberSize As String = oInvSummInfo("Subject").Value
Dim RevNumb As String = oInvSummInfo("Revision Number").Value
Dim oDocMat As MaterialAsset = oDoc.ActiveMaterial
Dim sMatName As String = oDocMat.DisplayName
Dim MatDensity As AssetValue = oDocMat.PhysicalPropertiesAsset.Item("structural_Density")
Dim oDensity As Double = MatDensity.Value

Dim Round As Inventor.Property
Try : Round = oInvUserInfo("Round_y") : Catch :	Round = oInvUserInfo.Add(1,"Round_y") :	End Try
Dim Round_y, inc As Double
Round_y = Round.Value
If Round_y <> 0 Then
	If Round_y > 0 And Round_y < 1 Then
		inc = Round_y
		Leng = Math.Round(Math.Round(L_size, 4) / inc) * inc
	ElseIf Round_y = 1 Then
		Leng = Math.Round(L_size)
	ElseIf Round_y > 1 And Round_y < 10 Then
		inc = Round_y / 10
		Leng = (Math.Round(Math.Round((L_size / 10), 4) / inc) * inc) * 10
	ElseIf Round_y >= 10 And Round_y < 100 Then
		inc = Round_y / 100
		Leng = (Ceil(Math.Round((L_size / 100), 4) / inc) * inc) * 100
	ElseIf Round_y >= 100 And Round_y < 1000 Then
		inc = Round_y / 1000
		Leng = (Ceil(Math.Round((L_size / 1000), 4) / inc) * inc) * 1000
	ElseIf Round_y >= 1000 Then
		inc = 0.1
		Leng = (Ceil(Math.Round((L_size / 10000), 4) / inc) * inc) * 10000
	End If
	
	If oDocSummInfo("Company").Value = "" Then
		If oInvSummInfo("Title").Value <> "" & RevNumb & " " & NumberSize & ", L=" & Leng & " мм" Then
			oInvSummInfo("Title").Value = "" & RevNumb & " " & NumberSize & ", L=" & Leng & " мм"
		End If
		If Round_y = 0 Then
			If oInvSummInfo("Title").Value <> sName.Remove(0, sName.IndexOf(" ") + 1) Then
				oInvSummInfo("Title").Value = sName.Remove(0, sName.IndexOf(" ") + 1)
			End If
		End If
	End If
	Try : oInvUserInfo("Main_size").Value = Leng / 1000 : Catch : oInvUserInfo.Add(Leng / 1000, "Main_size") : End Try
End If
Try : oInvUserInfo("Stren_steel").Value = sMatName.Substring(0, sMatName.IndexOf(" "))
Catch : oInvUserInfo.Add(sMatName.Substring(0, sMatName.IndexOf(" ")), "Stren_steel") : End Try 'Клас міцності
Try : oInvUserInfo("Stan_steel").Value = sMatName.Remove(0, sMatName.IndexOf(" ") + 1)
Catch : oInvUserInfo.Add(sMatName.Remove(0, sMatName.IndexOf(" ") + 1), "Stan_steel") : End Try 'Стандарт матеріала
Dim Area_Part As Double
If WebLink = "ДСТУ EN 10210-2" Or WebLink = "ДСТУ EN 10216-1" Or WebLink = "ДСТУ ISO 1127" Or WebLink = "ДСТУ 8936" Or WebLink = "ДСТУ 8938" _
	Or WebLink = "ДСТУ 8939" Or WebLink = "ДСТУ 8940" Or WebLink = "ДСТУ 8943" Or WebLink = "ДСТУ Б В.2.6-8-95" Then
	If Math.Round(Measure.ExtentsWidth, 2) <> Math.Round(Measure.ExtentsLength, 2) Then
		Area_Part = ((Parameter("G_H") -(Parameter("G_IR") * 2)) * 2 + (Parameter("G_W") -(Parameter("G_IR") * 2)) * 2) + (PI * Parameter("G_IR") * 2)
	Else
		Area_Part = PI * Parameter("G_H")
	End If
Else
	Area_Part = iProperties.Area / Measure.ExtentsHeight
End If
Try : oInvUserInfo("Area_Color").Value = Math.Round((Measure.ExtentsHeight * Area_Part) / 1000000, 3)
Catch : oInvUserInfo.Add(Math.Round((Measure.ExtentsHeight * Area_Part) / 1000000, 3), "Area_Color") : End Try
